FROM node:alpine as builder

COPY package.json /usr/local/app/package.json
WORKDIR /usr/local/app

RUN yarn install --prod

FROM arm64v8/node:alpine

ADD ./ /usr/local/app
WORKDIR /usr/local/app

RUN chmod -R 777 /usr/local/app

COPY --from=builder /usr/local/app/node_modules /usr/local/app/node_modules

EXPOSE 80 8001 8002

CMD ["yarn", "start"]