FROM node:alpine as builder

COPY package.json /usr/local/app/package.json
WORKDIR /usr/local/app

RUN yarn install --prod

FROM arm64v8/node:alpine

ADD ./ /usr/local/app
WORKDIR /usr/local/app

COPY --from=builder /usr/local/app/node_modules /usr/local/app/node_modules

ENV PATH /usr/local/app/node_modules/.bin:$PATH

EXPOSE 80 8001 8002

CMD ["pm2-runtime", "index.js"]