FROM node:alpine as builder

COPY package.json /usr/local/app/package.json
WORKDIR /usr/local/app

RUN yarn install --prod

FROM arm32v7/node:alpine

ADD ./ /usr/local/app
WORKDIR /usr/local/app

COPY --from=builder /usr/local/app/node_modules /usr/local/app/node_modules

RUN ["/bin/bash", "-c", "chmod -R 777 /usr/local/app"]

EXPOSE 80 8001 8002

CMD ["node", "index.js"]