FROM node:alpine as builder

COPY package.json /usr/local/app/package.json
WORKDIR /usr/local/app

RUN yarn install --prod

FROM arm64v8/node:alpine

ADD ./ /usr/local/app
WORKDIR /usr/local/app

USER node
COPY --from=builder /usr/local/app/node_modules /usr/local/app/node_modules

RUN ["chmod", "755", "/usr/local/app"]

EXPOSE 80 8001 8002

CMD ["node", "index.js"]